### PR TITLE
Added scala3 support for akka

### PR DESCRIPTION
**Pull request by Pask423**
Scala 3 support required for https://github.com/softwaremill/sttp/issues/1225

### CODE REVIEW

**Comment by adamw** [comment]
Looks good, ship it :) To satisfy mima you'll have to add a temporary work-around like in `zio1`, and remove (both in fact) after the release: `Seq(mimaPreviousArtifacts := Set.empty) // for now, there are no previous artifacts`

**Comment by Pask423** [comment]
Maybe in the process of cleaning up ZIO we can rename `zio1` to sth more meaningful ?

**Comment by adamw** [comment]
zio1 is quite meaningful I guess, it's integration with zio version 1, unlike the zio module, which integrates with latest zio (version 2)

**Comment by Pask423** [comment]
ok for me then

**Review by adamw — APPROVED** [review]

**Pull request merged**
